### ISSUE TITLE
could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by kelrose** [linonetwo/MOSS-DockerFile#2]
我是在Ubuntu下docker运行的：
docker run --gpus all -it --volume=/home/moss-moon-003-sft-plugin-int4:/mnt/llm -d linonetwo/moss:int4
提示报错，请问如何解决？

**Comment by kelrose** [comment]
docker gpu

**Comment by yhyu13** [comment]
怎么解决的？cudatoolkit没装？
