### ISSUE TITLE
请问运行后的访问端口是多少啊

### ISSUE THREAD

**Issue by tiamohf** [linonetwo/MOSS-DockerFile#6]

**Comment by tiamohf** [comment]
运行后看到了
![image](https://github.com/linonetwo/MOSS-DockerFile/assets/33214450/046edd1d-9e7f-4a4c-8b06-900b3a73b34c)

**Comment by linonetwo** [comment]
是的

**Comment by tiamohf** [comment]
docker run --gpus all -it --volume=/home/q/cain/moss:/mnt/llm/MOSS -p 7868:7860 -d moss

但是这样启动成功了，不能访问
